# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0ba78081e51f17f54a1d1f779f47c19c"
application_url = "https://entrance-occasions-preceding-lamb.trycloudflare.com"
embedded = true
name = "Sale Badge Application"
handle = "sale-badge-application"

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://entrance-occasions-preceding-lamb.trycloudflare.com/auth/callback",
  "https://entrance-occasions-preceding-lamb.trycloudflare.com/auth/shopify/callback",
  "https://entrance-occasions-preceding-lamb.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "bytesteststore.myshopify.com"
automatically_update_urls_on_dev = true
